//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEMO.API.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages_es_ES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages_es_ES() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DEMO.API.Resources.Messages-es-ES", typeof(Messages_es_ES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field: {0} contains incorrect values. Incorrect Value: {1}.
        /// </summary>
        internal static string DOMAIN_INCORECT_VALUES {
            get {
                return ResourceManager.GetString("DOMAIN_INCORECT_VALUES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty message for {0}.
        /// </summary>
        internal static string EMPTY_MESSAGE {
            get {
                return ResourceManager.GetString("EMPTY MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field: {0} is mandatory.
        /// </summary>
        internal static string FIELD_MANDATORY {
            get {
                return ResourceManager.GetString("FIELD_MANDATORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field: {0} contains incorrect values.
        /// </summary>
        internal static string INCORRECT_VALUES {
            get {
                return ResourceManager.GetString("INCORRECT_VALUES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field: {0} length is greather than {1}.
        /// </summary>
        internal static string MAXIMUN_STRING_LENGTH {
            get {
                return ResourceManager.GetString("MAXIMUN_STRING_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource for the employeeId {0} and periodId {1} does not exists.
        /// </summary>
        internal static string RESOURCE_NOT_EXISTS {
            get {
                return ResourceManager.GetString("RESOURCE_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user with email {0} is already associated with other resource {1}.
        /// </summary>
        internal static string USER_ASSOCIATE_WITH_OTHER_RESOURCE {
            get {
                return ResourceManager.GetString("USER_ASSOCIATE_WITH_OTHER_RESOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user for the resource with mail {0} does not exists.
        /// </summary>
        internal static string USER_NOT_EXISTS {
            get {
                return ResourceManager.GetString("USER_NOT_EXISTS", resourceCulture);
            }
        }
    }
}
