//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEMO.API.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DEMO.API.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch message for JobNumber {0} is empty.
        /// </summary>
        internal static string BATCH_MESSAGE_EMPTY {
            get {
                return ResourceManager.GetString("BATCH_MESSAGE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field: {0} contains incorrect values. Incorrect Value: {1}.
        /// </summary>
        internal static string DOMAIN_INCORECT_VALUES {
            get {
                return ResourceManager.GetString("DOMAIN_INCORECT_VALUES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty message for {0}.
        /// </summary>
        internal static string EMPTY_MESSAGE {
            get {
                return ResourceManager.GetString("EMPTY_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The timeentry with id {0} can not send to Planner because is not approved.
        /// </summary>
        internal static string EXPORT_TIME_ENTRY_PLANNER_NOT_APPROVED {
            get {
                return ResourceManager.GetString("EXPORT_TIME_ENTRY_PLANNER_NOT_APPROVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The timeentry with id {0} can not send to Planner because is does not all contain economic fields.
        /// </summary>
        internal static string EXPORT_TIME_ENTRY_PLANNER_NOT_ECONOMIC_FIELDS {
            get {
                return ResourceManager.GetString("EXPORT_TIME_ENTRY_PLANNER_NOT_ECONOMIC_FIELDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field: {0} is mandatory.
        /// </summary>
        internal static string FIELD_MANDATORY {
            get {
                return ResourceManager.GetString("FIELD_MANDATORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exists time entries overlap in the guard period. If you continue, this timeentries will set with the guard check are you sure?.
        /// </summary>
        internal static string GUARD_EXISTS_TIMEENTRIES {
            get {
                return ResourceManager.GetString("GUARD_EXISTS_TIMEENTRIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t save the record bacause the dates overlap with other existing by the same resource. Please, review existing records..
        /// </summary>
        internal static string GUARD_OVERLAP {
            get {
                return ResourceManager.GetString("GUARD_OVERLAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The guard end date cannot be earlier than the start date.
        /// </summary>
        internal static string GUARD_RANGE_INCORRECT {
            get {
                return ResourceManager.GetString("GUARD_RANGE_INCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The check &quot;Guard&quot; will remove in existint time entries, are you sure?.
        /// </summary>
        internal static string GUARD_REMOVE_TIMEENTRIES {
            get {
                return ResourceManager.GetString("GUARD_REMOVE_TIMEENTRIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field: {0} contains incorrect values.
        /// </summary>
        internal static string INCORRECT_VALUES {
            get {
                return ResourceManager.GetString("INCORRECT_VALUES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field: {0} length is greather than {1}.
        /// </summary>
        internal static string MAXIMUN_STRING_LENGTH {
            get {
                return ResourceManager.GetString("MAXIMUN_STRING_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error to send batch messages to Azure Service Bus. Topic {0}. Message {1}.
        /// </summary>
        internal static string MESSAGE_SERVICEBUS_BATCH_ERROR {
            get {
                return ResourceManager.GetString("MESSAGE_SERVICEBUS_BATCH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error to send message to buffer (Azure Service Bus). Unique Message too large (more than 256KB).
        /// </summary>
        internal static string MESSAGE_SERVICEBUS_NOTFIT {
            get {
                return ResourceManager.GetString("MESSAGE_SERVICEBUS_NOTFIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource for the employeeId {0} and periodId {1} does not exists.
        /// </summary>
        internal static string RESOURCE_NOT_EXISTS {
            get {
                return ResourceManager.GetString("RESOURCE_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation: Send communication request to SOC has fail.
        /// </summary>
        internal static string SOC_SEND_COMMUNICATION_FAIL {
            get {
                return ResourceManager.GetString("SOC_SEND_COMMUNICATION_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The time entry with id {0} does not exists.
        /// </summary>
        internal static string TIME_ENTRY_NOT_EXISTS {
            get {
                return ResourceManager.GetString("TIME_ENTRY_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user with email {0} is already associated with other resource {1}.
        /// </summary>
        internal static string USER_ASSOCIATE_WITH_OTHER_RESOURCE {
            get {
                return ResourceManager.GetString("USER_ASSOCIATE_WITH_OTHER_RESOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user for the resource with mail {0} does not exists.
        /// </summary>
        internal static string USER_NOT_EXISTS {
            get {
                return ResourceManager.GetString("USER_NOT_EXISTS", resourceCulture);
            }
        }
    }
}
